name: .NET Core CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.102
          
      - name: Install dependencies
        run: dotnet restore
        working-directory: Online_Market_App 5
        
      - name: Build 
        run: dotnet build --configuration Release 
        working-directory: Online_Market_App 5
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: Online_Market_App 5
